# Generated by Django 5.0.14 on 2026-06-29 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_registration_verification_fields'),
        ('users', '0002_rename_avatar_to_avatar_url'),
    ]

    operations = [
    ]
