# Generated by Django 4.2.30 on 2026-06-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_merge_20260629_1126"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.CharField(max_length=45, unique=True)),
                ("attempts_count", models.IntegerField(default=0)),
                ("last_attempt", models.DateTimeField()),
                ("blocked_until", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Intento de Login",
                "verbose_name_plural": "Intentos de Login",
            },
        ),
    ]
