# Generated by Django 4.2.30 on 2026-06-30 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coreografia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                ("genero", models.CharField(max_length=100)),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("principiante", "Principiante"),
                            ("intermedio", "Intermedio"),
                            ("avanzado", "Avanzado"),
                        ],
                        default="principiante",
                        max_length=20,
                    ),
                ),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("video_url", models.CharField(blank=True, max_length=500)),
                ("thumbnail_url", models.CharField(blank=True, max_length=500)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("publicado", "Publicado"),
                            ("archivado", "Archivado"),
                        ],
                        default="borrador",
                        max_length=20,
                    ),
                ),
                ("duracion_segundos", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profesor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coreografias",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Coreografía",
                "verbose_name_plural": "Coreografías",
                "db_table": "catalog_coreografia",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=500)),
                ("duracion_segundos", models.PositiveIntegerField(default=0)),
                ("orden", models.PositiveSmallIntegerField(default=1)),
                (
                    "coreografia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="catalog.coreografia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video",
                "verbose_name_plural": "Videos",
                "db_table": "catalog_video",
                "ordering": ["orden"],
            },
        ),
    ]
