# Generated by Django 5.0.14 on 2026-07-13 04:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_reemplazar_genero_texto_por_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="coreografia",
            name="preview_segundos",
            field=models.IntegerField(default=30),
        ),
        migrations.AddIndex(
            model_name="coreografia",
            index=models.Index(fields=["estado"], name="catalog_cor_estado_c2d085_idx"),
        ),
        migrations.AddIndex(
            model_name="coreografia",
            index=models.Index(fields=["nivel"], name="catalog_cor_nivel_c25f91_idx"),
        ),
        migrations.AddIndex(
            model_name="coreografia",
            index=models.Index(fields=["precio"], name="catalog_cor_precio_4a9ea1_idx"),
        ),
        migrations.AddIndex(
            model_name="coreografia",
            index=models.Index(
                fields=["genero"], name="catalog_cor_genero__360d6b_idx"
            ),
        ),
    ]
