# Generated by Django 4.2.30 on 2026-06-30 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_coreografia_y_video_inicial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Compra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("precio_pagado", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("activa", "Activa"),
                            ("cancelada", "Cancelada"),
                            ("reembolsada", "Reembolsada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("fecha_compra", models.DateTimeField(auto_now_add=True)),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[
                            ("tarjeta", "Tarjeta de crédito/débito"),
                            ("transferencia", "Transferencia bancaria"),
                            ("efectivo", "Efectivo"),
                            ("otro", "Otro"),
                        ],
                        default="tarjeta",
                        max_length=20,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compras",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "coreografia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compras",
                        to="catalog.coreografia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compra",
                "verbose_name_plural": "Compras",
                "db_table": "sales_compra",
                "ordering": ["-fecha_compra"],
            },
        ),
    ]
