# Generated by Django 5.0.14 on 2026-07-13 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_preview_segundos_e_indices"),
        ("sales", "0002_carrito_y_carrito_item"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Orden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "estado",
                    models.CharField(
                        choices=[("completada", "Completada"), ("fallida", "Fallida")],
                        default="completada",
                        max_length=20,
                    ),
                ),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[
                            ("pse", "PSE (Débito bancario)"),
                            ("tarjeta", "Tarjeta de crédito/débito"),
                        ],
                        max_length=20,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=100, unique=True)),
                ("datos_facturacion", models.JSONField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordenes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden",
                "verbose_name_plural": "Órdenes",
                "db_table": "sales_orden",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="OrdenItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("precio_pagado", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "coreografia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orden_items",
                        to="catalog.coreografia",
                    ),
                ),
                (
                    "orden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.orden",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de orden",
                "verbose_name_plural": "Ítems de orden",
                "db_table": "sales_orden_item",
                "unique_together": {("orden", "coreografia")},
            },
        ),
    ]
