# Generated by Django 5.0.14 on 2026-07-13 08:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_preview_segundos_e_indices"),
        ("sales", "0003_orden_y_orden_item"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="compra",
            index=models.Index(
                fields=["fecha_compra"], name="sales_compr_fecha_c_c159ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="compra",
            index=models.Index(
                fields=["coreografia"], name="sales_compr_coreogr_d6c3c0_idx"
            ),
        ),
    ]
